// ── Title image ───────────────────────────────────────────────────────────────
// To change the header image, update this URL.
const title = "https://domf5oio6qrcr.cloudfront.net/medialibrary/11525/0a5ae820-7051-4495-bcca-61bf02897472.jpg";
document.getElementById("title-img").src = title;

// ── DOM references ────────────────────────────────────────────────────────────
const imgEl   = document.getElementById("comic-img");
const dateEl  = document.getElementById("comic-date");
const btnPrev = document.getElementById("btn-prev");
const btnNext = document.getElementById("btn-next");
const btnRand = document.getElementById("btn-random");
const emptyMsg = document.getElementById("empty-msg");

// ── State ─────────────────────────────────────────────────────────────────────
let comics = [];
let currentIndex = 0;

// ── Month name → index map (for sorting) ─────────────────────────────────────
const MONTH_ORDER = {
  january: 0, february: 1, march: 2, april: 3,
  may: 4, june: 5, july: 6, august: 7,
  september: 8, october: 9, november: 10, december: 11
};

// ── Load comics from manifest.json ───────────────────────────────────────────
// Photos must be named:  Month_Day_Year.jpeg
// Example:               January_5_2025.jpeg
//
// manifest.json is auto-generated by a GitHub Action whenever a photo is
// pushed to the photos/ folder. Locally, start.command regenerates it too.

async function loadComics() {
  const res = await fetch("manifest.json");
  const files = await res.json(); // array of filenames, e.g. ["January_5_2025.jpeg"]

  const entries = [];

  files.forEach(filename => {
    const match = filename.match(/^([A-Za-z]+)_(\d+)_(\d{4})\.jpe?g$/i);

    if (!match) return;

    const [, month, day, year] = match;
    const monthIndex = MONTH_ORDER[month.toLowerCase()];
    if (monthIndex === undefined) return;

    const capitalized = month.charAt(0).toUpperCase() + month.slice(1).toLowerCase();
    const dateStr = `${capitalized} ${parseInt(day, 10)}, ${year}`;

    entries.push({
      src:     "photos/" + filename,
      date:    dateStr,
      sortKey: new Date(+year, monthIndex, +day)
    });
  });

  // Oldest first so Prev/Next feel chronological
  entries.sort((a, b) => a.sortKey - b.sortKey);
  return entries;
}

// ── Display helpers ───────────────────────────────────────────────────────────
function showComic(index) {
  currentIndex        = index;
  imgEl.src           = comics[index].src;
  imgEl.alt           = "Anita Comic — " + comics[index].date;
  dateEl.textContent  = comics[index].date;
  imgEl.style.display = "block";
  emptyMsg.style.display = "none";
  btnPrev.disabled    = index === 0;
  btnNext.disabled    = index === comics.length - 1;
  btnRand.disabled    = false;
}

function showEmpty(message) {
  dateEl.textContent     = "";
  imgEl.style.display    = "none";
  emptyMsg.textContent   = message;
  emptyMsg.style.display = "block";
  btnPrev.disabled = btnNext.disabled = btnRand.disabled = true;
}

// ── Button handlers ───────────────────────────────────────────────────────────
btnPrev.addEventListener("click", () => {
  if (currentIndex > 0) showComic(currentIndex - 1);
});

btnNext.addEventListener("click", () => {
  if (currentIndex < comics.length - 1) showComic(currentIndex + 1);
});

btnRand.addEventListener("click", () => {
  showComic(Math.floor(Math.random() * comics.length));
});

// ── Init ──────────────────────────────────────────────────────────────────────
loadComics()
  .then(entries => {
    comics = entries;
    if (comics.length === 0) {
      showEmpty("No comics yet — drop a .jpeg into the photos/ folder and refresh!");
    } else {
      showComic(comics.length - 1); // start on the most recent comic
    }
  })
  .catch(() => {
    showEmpty(
      "⚠️ Could not load comics. If running locally, double-click start.command " +
      "instead of opening index.html directly."
    );
  });
